baseURL                = "https://zonkidd-shao.github.io/"
locale                 = "zh-cn"
title                  = "Zonkidd 的技术博客"
theme                  = "hugo-theme-stack"
hasCJKLanguage         = true
enableEmoji            = true

[pagination]
  pagerSize = 10

[permalinks]
  post = "/p/:slug/"
  page = "/:slug/"

[params]
  mainSections   = ["post"]
  rssFullContent = true
  favicon        = ""

  [params.footer]
    since = 2025

  [params.sidebar]
    emoji    = "🚀"
    subtitle = "记录代码、探索技术、分享思考"

  [params.article]
    [params.article.license]
      enabled = false

  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "categories", params = { limit = 20 } },
      { type = "archives", params = { limit = 5 } },
      { type = "tag-cloud", params = { limit = 20 } },
    ]
    page = [{ type = "toc" }]

[[menu.main]]
  identifier = "home"
  name       = "首页"
  url        = "/"
  weight     = 10

[[menu.main]]
  identifier = "categories"
  name       = "分类"
  url        = "/categories/"
  weight     = 20

[[menu.main]]
  identifier = "tags"
  name       = "标签"
  url        = "/tags/"
  weight     = 30

[[menu.main]]
  identifier = "archives"
  name       = "归档"
  url        = "/archives/"
  weight     = 40

[[menu.main]]
  identifier = "search"
  name       = "搜索"
  url        = "/search/"
  weight     = 50

[[menu.main]]
  identifier = "about"
  name       = "关于"
  url        = "/about/"
  weight     = 60

[[menu.social]]
  identifier = "github"
  name       = "GitHub"
  url        = "https://github.com/Zonkidd-Shao"
  params = { icon = "brand-github" }

[[menu.social]]
  identifier = "email"
  name       = "Email"
  url        = "mailto:zonkidd.shao@foxmail.com"
  params = { icon = "user" }
